coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.3
    patch:
      default:
        target: 85
comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false