services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: enhanced-redis-session-handler-app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/app/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - REDIS_HOST=storage
      - REDIS_PORT=6379
    depends_on:
      - storage
    networks:
      - app-network

  storage:
    image: valkey/valkey:latest
    container_name: enhanced-redis-session-handler-storage
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
    networks:
      - app-network
    command: valkey-server --appendonly yes

volumes:
  valkey-data:
    driver: local

networks:
  app-network:
    driver: bridge
