services:
  app:
    build:
      context: ..
      dockerfile: docker/app/Dockerfile
    container_name: enhanced-redis-session-handler-app
    ports:
      - "8080:80"
    volumes:
      - ../:/var/www/html
      - ./app/php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - REDIS_HOST=storage
      - REDIS_PORT=6379
      - REDIS_FALLBACK_HOST=storage-fallback
      - REDIS_FALLBACK_PORT=6379
      - SESSION_REDIS_HOST=storage
      - SESSION_REDIS_PORT=6379
    depends_on:
      - storage
      - storage-fallback
    networks:
      - app-network

  storage:
    image: valkey/valkey:latest
    container_name: enhanced-redis-session-handler-storage
    ports:
      - "6379:6379"
    volumes:
      - valkey-data:/data
    networks:
      - app-network
    command: valkey-server --appendonly yes

  storage-fallback:
    image: valkey/valkey:latest
    container_name: enhanced-redis-session-handler-storage-fallback
    ports:
      - "6380:6379"
    volumes:
      - valkey-fallback-data:/data
    networks:
      - app-network
    command: valkey-server --appendonly yes

volumes:
  valkey-data:
    driver: local
  valkey-fallback-data:
    driver: local

networks:
  app-network:
    driver: bridge
